# Base colors
background #1D282F
foreground #DBD0C6

# Cursor
cursor #DBD0C6
cursor_text_color #1D282F

# Selection
selection_background #223B49
selection_foreground #DBD0C6

# ANSI colors
color0  #1D282F
color8  #568270

color1  #FF5B61
color9  #D48588

color2  #86BFD2
color10 #A7CBEA

color3  #FFCF99
color11 #FDD9AF

color4  #9DC6A9
color12 #95C2A1

color5  #D59CCE
color13 #D9ADD4

color6  #79C2B6
color14 #87CBB1

color7  #91A4AD
color15 #DBD0C6
