# Kanagawa Dark 
general {
    gaps_in = 2
    gaps_out = 5

    border_size = 2

    # Active window border (golden accent)
    col.active_border = rgba(e6c384aa)

    # Inactive window border (dark panel)
    col.inactive_border = rgba(1f1f28aa)

    # Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = true

    # Please see https://wiki.hypr.land/Configuring/Tearing/ before you turn this on
    allow_tearing = false

    layout = dwindle
}
